site_name: 1132 德文法學
docs_dir: 課堂筆記


theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.footer        # 產生頁腳的上一頁/下一頁


font:
  text: Noto Serif CJK TC
  code: JetBrains Mono
plugins:
  - search
  - awesome-pages
  - exclude:
      glob: ['_*/**', '*_.md']
extra_css:
  - assets/extra.css   # 若有

extra_javascript:
  - assets/keynav.js           # 我將放置的鍵盤導航腳本
  - assets/extra.js